import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root application layout that applies global fonts and wraps page content with Providers.
 *
 * @param children - The React nodes to render inside the application's Providers.
 * @returns The top-level HTML structure (`<html lang="en">` with a `<body>` applying font and antialiasing classes) containing the Providers-wrapped `children`.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
          <Providers>
          {children}
      </Providers>
        </body>
    </html>
  );
}